language: generic
before_install:
  - docker pull jacktasia/dumb-jump-test-runner:latest
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  # - EVM_EMACS=emacs-24.5-travis
  # - EVM_EMACS=emacs-25.1-travis
  # - EVM_EMACS=emacs-25.2-travis
  # - EVM_EMACS=emacs-26.1-travis
script:
  # - rg --version
  # - ag --version
  # - grep --version
  # - emacs --version
  # - git --version
  # - make test-concurrent
  - docker run -i -e EVM_EMACS=$EVM_EMACS -v /tmp/dumb-jump:/home/travis/dumb-jump jacktasia/dumb-jump-test-runner:latest
